language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
addons:
  apt:
    packages:
    # BLAS support
    - liblapack3gf
    - libblas3gf
    - liblapack-dev
    - libblas-dev
    - libatlas-base-dev

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib nose seaborn statsmodels
  - conda install --yes -c https://conda.binstar.org/omnia numdifftools
  - pip install git+git://github.com/khrapovs/mygmm
  - python setup.py build

# Run test
script:
  - python setup.py develop
  - nosetests

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
