language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
notifications:
  email:
    on_success: change
    on_failure: always
sudo: false
addons:
  apt:
    packages:
    # BLAS support
    - liblapack3gf
    - libblas3gf
    - liblapack-dev
    - libblas-dev
    - libatlas-base-dev

# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION cython numpy scipy matplotlib nose seaborn statsmodels
  - source activate test-environment

# Install packages
install:
  - conda install --yes -c omnia numdifftools
  - pip install git+git://github.com/khrapovs/mygmm
  - python setup.py build

# Run test
script:
  - python setup.py develop
  - nosetests

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
